services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LOCALHOST_FOR_BACKEND://localhost:9092,LISTENER_UI://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LOCALHOST_FOR_BACKEND:PLAINTEXT,LISTENER_UI:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCALHOST_FOR_BACKEND
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.1
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      
  loki:
    image: grafana/loki:3.2.0
    ports:
      - "3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  vm:
    image: victoriametrics/victoria-metrics:v1.104.0
    ports:
      - "8428"
    volumes:
      - vm-storage:/victoria-metrics-data

  tempo:
    image: grafana/tempo:2.6.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3200"
      - "4318"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-storage:/var/tempo

  grafana:
    image: grafana/grafana:11.2.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

  otel:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
  
volumes:
  grafana-storage:
  vm-storage:
  tempo-storage: