receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: detailed
  otlphttp/victoriametrics:
    compression: gzip
    encoding: proto
    endpoint: http://vm:8428/opentelemetry
    tls:
      insecure: true
  otlphttp:
    logs_endpoint: http://loki:3100/otlp/v1/logs
    traces_endpoint: http://tempo:4318/v1/traces

service:
  pipelines:
    logs:
      receivers: [ otlp ]
      exporters: [ otlphttp ]
    traces:
      receivers: [ otlp ]
      exporters: [ otlphttp ]
    metrics:   
      receivers: [otlp] 
      exporters: [otlphttp/victoriametrics]
